default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>

development:
  <<: *default
  database: ecx_wallet_development

test:
  <<: *default
  database: ecx_wallet_test

production:
  <<: *default
  database: ecx_wallet_production
  username: ecx_wallet
  password: <%= ENV["ECX_WALLET_DATABASE_PASSWORD"] %>
